package com.techleads.app.commons;

public interface DBQueries {

	String INSERT_USERS = "INSERT INTO USERS ( ID, NAME, CITY, UUID_CODE ) VALUES ( HIBERNATE_SEQUENCE.NEXTVAL, :name, :address, :uuid)";
	String INSERT_FILE_DATA="INSERT INTO UPLOADFILE ( ID,NAME, FILE_UPLOAD, FILE_PATH,CONTENT_TYP,USER_ID ) VALUES ( HIBERNATE_SEQUENCE.NEXTVAL,:fileName, :file_content, :filePath, :contentType, :userId )";
	String SELECT_MAX_ID_RECORD="SELECT E.ID, E.NAME, E.CITY,E.UUID_CODE, F.ID as FID,  F.NAME as FNAME, F.FILE_PATH, F.CONTENT_TYP, F.USER_ID FROM USERS E, UPLOADFILE F WHERE E.ID=(SELECT MAX(ID) FROM USERS ) AND E.ID= F.USER_ID";
	String FILE_DOWNLOAD_BY_UUID="SELECT F.NAME,F.FILE_UPLOAD, F.FILE_PATH, F.CONTENT_TYP FROM USERS E, UPLOADFILE F WHERE E.ID=F.USER_ID AND E.UUID_CODE=:uuidCode";
}
